title: Ethan's Portfolio
author:
  name: Yuan Yi (Ethan)
  email: 203*****57@qq.com
description: > # this means to ignore newlines until "show_excerpts:"
  A web page where an architecture student records work.

  Address: Wenzhou-Kean University
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: 
    github:  EVA0211
    # devto: jekyll
    # dribbble: 
    # facebook: 
    # flickr:   
    instagram: yuanyi4750
    # linkedin: 
    # pinterest: 
    # youtube: 
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # keybase: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

    # GitLab instances
    # gitlab:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima


plugins:
 - jekyll-feed
 - jekyll-seo-tag
